// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || 'https://bwenopgoshivacvehcla.supabase.co';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3ZW5vcGdvc2hpdmFjdmVoY2xhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTAxMzksImV4cCI6MjA2ODY2NjEzOX0.RtTh6nbQtyyNvwZNIMfLazVouBoqTcG9Ps12jj8-Dvo';

export const supabase = createClient(supabaseUrl, supabaseAnonKey);